name: Build and Push

permissions:
    contents: read
    packages: write

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    build:
        runs-on: ${{ vars.RUNNERS }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            
            - name: Login to GHCR if needed
              run: |
                if ! grep -q "ghcr.io" ~/.docker/config.json 2>/dev/null; then
                  echo "GHCR not in config — logging in."
                  echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u USERNAME --password-stdin
                else
                  echo "GHCR already present in Docker config."
                fi

            - name: Run build script
              run: chmod +x ./build.sh && ./build.sh ${{ github.repository }}