name: Build and Push

permissions:
    contents: read
    packages: write

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    build:
        runs-on: self-hosted

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Run build script
              run: chmod +x ./build.sh && ./build.sh ${{ github.repository }}